services:
  # ==============================================
  # Service: n8n-db
  # PostgreSQL 16 Alpine for n8n
  # Persists data via Docker volume
  # ==============================================
  n8n-db:
    image: postgres:16-alpine
    container_name: n8n-db
    restart: always
    env_file:
      - .env
    volumes:
      - n8n_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10

  # ==============================================
  # Service: n8n
  # Principal d'exécution des workflows n8n
  # Monte un volume pour la configuration et les données
  # ==============================================
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: always
    depends_on:
      n8n-db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - n8n_data:/home/node/.n8n

  # ==============================================
  # Service: cloudflared
  # Tunnel Cloudflare pour exposer n8n en HTTPS
  # Gère automatiquement le tunnel configuré
  # ==============================================
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    env_file:
      - .env

  # ==============================================
  # Service: watchtower
  # Mise à jour automatique des conteneurs Docker
  # Vérifie et nettoie les images obsolètes toutes les 5 minutes
  # ==============================================
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 300

volumes:
  n8n_data:
  n8n_db_data:
